color_code_to_hex = {
    30: {"color_name": "berry_red", "hex": "#b8256f"},
    31: {"color_name": "red", "hex": "#db4035"},
    32: {"color_name": "orange", "hex": "#ff9933"},
    33: {"color_name": "yellow", "hex": "#fad000"},
    34: {"color_name": "olive_green", "hex": "#afb83b"},
    35: {"color_name": "lime_green", "hex": "#7ecc49"},
    36: {"color_name": "green", "hex": "#299438"},
    37: {"color_name": "mint_green", "hex": "#6accbc"},
    38: {"color_name": "teal", "hex": "#158fad"},
    39: {"color_name": "sky_blue", "hex": "#14aaf5"},
    40: {"color_name": "light_blue", "hex": "#96c3eb"},
    41: {"color_name": "blue", "hex": "#4073ff"},
    42: {"color_name": "grape", "hex": "#884dff"},
    43: {"color_name": "violet", "hex": "#af38eb"},
    44: {"color_name": "lavender", "hex": "#eb96eb"},
    45: {"color_name": "magenta", "hex": "#e05194"},
    46: {"color_name": "salmon", "hex": "#ff8d85"},
    47: {"color_name": "charcoal", "hex": "#808080"},
    48: {"color_name": "grey", "hex": "#b8b8b8"},
    49: {"color_name": "taupe", "hex": "#ccac93"},
}
